trigger: ["master"]
pr: ["master"]

jobs:
  - template: _build/azure-pipelines-template.yml
    parameters:
      name: macOS
      displayName: macOS SQLite
      vmImage: macOS-10.13
    setup:
      - bash: |
          brew update &&
          brew install sqlite
        displayName: Install sqlite
  - template: _build/azure-pipelines-template.yml
    parameters:
      name: Linux_sqlite
      displayName: Linux SQLite
      vmImage: ubuntu-16.04
    setup:
      - bash: |
          sudo apt-get update &&
          sudo apt-get -y install sqlite3 libsqlite3-dev
        displayName: Install sqlite
  - template: _build/azure-pipelines-template.yml
    parameters:
      name: Windows_sqlite
      displayName: Windows SQLite
      vmImage: vs2017-win2016
    setup:
      - script: |
          choco install 7zip
          mkdir C:\sqlite
          CD /D C:\sqlite
          curl -fsS --retry 3 --retry-connrefused -o sqlite3.zip https://sqlite.org/2017/sqlite-dll-win64-x64-3160200.zip
          7z e sqlite3.zip -y
          call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          lib /machine:x64 /def:sqlite3.def /out:sqlite3.lib
          set PATH=%PATH%;C:\sqlite
          echo "##vso[task.setvariable variable=PATH;]%PATH%;C:\sqlite"
        displayName: Install sqlite
