strategy:
  matrix:
    windows-stable:
      imageName: "vs2017-win2016"
      rustup_toolchain: stable
    # mac-stable:
    #   imageName: "macos-10.13"
    #   rustup_toolchain: stable
    # linux-stable:
    #   imageName: "ubuntu-16.04"
    #   rustup_toolchain: stable
pool:
  vmImage: $(imageName)

steps:
  - ${{ parameters.setup }}
  - template: '_build/install-rust.yml'
    parameters:
      platform: ${{parameters.name}}
      rust_version: $(RUSTUP_TOOLCHAIN)  
  - template: '_build/install-sqlite.yml'
  - script: npm run prod:rust
