[package]
name = "pustaka-rs"
version = "0.1.0"
authors = ["Abadi Kurniawan <abadi.kurniawan@gmail.com>"]

# bin is the entry point for `cargo run` or `cargo build`
[[bin]]
name = "pustaka"
path = "src/server/bin/main.rs"

# [[bin]]
# name = "seed"
# path = "src/server/bin/seed.rs"

[lib]
name = "pustaka_lib"
path = "src/server/lib.rs"

[dependencies]
rocket = "0.3.3"
rocket_codegen = "0.3.3"
diesel = { version = "0.16.0", features = ["sqlite"] }
diesel_codegen = { version = "0.16.0", features = ["sqlite"] }
dotenv = "0.9.0"
r2d2 = "*"
r2d2-diesel = "*"