[package]
name = "pustaka-rs"
version = "0.1.0"
authors = ["Abadi Kurniawan <abadi.kurniawan@gmail.com>"]

# bin is the entry point for `cargo run` or `cargo build`
[[bin]]
name = "pustaka"
path = "src/server/main.rs"

[lib]
name = "pustaka_lib"
path = "src/server/lib.rs"

[dependencies]
rocket = "0.3.3"
rocket_codegen = "0.3.3"
diesel = { version = "0.16.0", features = ["sqlite"] }
diesel_codegen = { version = "0.16.0", features = ["sqlite"] }
dotenv = "0.9.0"