DROP TABLE category;
DROP TABLE media_type;
DROP TABLE author;
DROP TABLE publication;
DROP TABLE publication_category;
DROP TABLE publication_tag;
DROP TABLE tag;
DROP TABLE favorite_category;
DROP TABLE user;