jobs:
  - job: ${{ parameters.name }}
    workspace:
      clean: all
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      ${{ insert }}: ${{ parameters.variables }}
    strategy:
      # 10 parallel builds are free, so use 10
      maxParallel: 10
      matrix:
        stable:
          rustup_toolchain: stable
    steps:
      - ${{ parameters.setup }}
      - template: install.yml
        parameters:
          platform: ${{parameters.name}}
          rust_version: $(RUSTUP_TOOLCHAIN)
      - bash: |
          echo $PATH
          echo $SQLITE3_LIB_DIR
        displayName: Sanity check path
      - bash: |
          cargo build --bins --release
        displayName: Building Server
      - bash: |
          node --version
          npm version
        displayName: Query node & npm versions
      - bash: |
          npm install
          npm run prod:client
        displayName: Building Client
      - bash: |
          diesel migration run --database-url pustaka.db
        displayName: Creating Database
      - template: github-release.yml
        parameters:
          platform: ${{parameters.name}}
