jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      ${{ insert }}: ${{ parameters.variables }}
    strategy:
      # 10 parallel builds are free, so use 10
      maxParallel: 10
      matrix:
        stable:
          rustup_toolchain: stable
    steps:
      - ${{ parameters.setup }}
      - template: install-rust.yml
        parameters:
          platform: ${{parameters.name}}
          rust_version: $(RUSTUP_TOOLCHAIN)
      - bash: |
          echo $PATH
        displayName: Sanity check path
      - bash: |
          mkdir dist
          cargo build --bins --release
          npm install
          npm run prod
        displayName: Building
      - ${{ if not(startsWith(parameters.platform, 'Windows')) }}:
        - bash: |
            cp target/release/pustaka dist
            cp target/release/seed dist
            cp target/release/scanner dist
          displayName: Copy binaries 
      - ${{ if startsWith(parameters.platform, 'Windows') }}:
        - bash: |
            cp target/release/*.exe dist
          displayName: Copy binaries (Windows)
      - bash: |
          cp -R app dist
          ls -R dist
        displayName: Copy assets
 