jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    strategy:
      # 10 parallel builds are free, so use 10
      maxParallel: 10
      matrix:
        stable:
          rustup_toolchain: stable
    steps:
      - ${{ parameters.setup }}
      - template: install-rust.yml
        parameters:
          platform: ${{parameters.name}}
          rust_version: $(RUSTUP_TOOLCHAIN)
      - bash: |
          echo $PATH
        displayName: Sanity check path
      - bash: |
          cargo -V
      - bash: |
          cargo build --bin pustaka --release